### ISSUE TITLE
Missing some...

### ISSUE THREAD

**Issue by thytetgc** [EvilDindon/ES-THEME-ARCADEPLANET#1]
Great work, very beautiful and well organized, congratulations!

However, some systems are missing.

Satellaview
MSX2
Commodere VIC 20

**Comment by thytetgc** [comment]
Great! All now work!

However, the _Commodore VIC 20_ only works if I copy the files from **cs20** and paste with the name **vic20**.

**Comment by EvilDindon** [comment]
which system ? Retrobat, Batocera or Emuelec ?


Le jeu. 14 avr. 2022 à 15:11, Thiago Castro ***@***.***> a
écrit :

**Comment by thytetgc** [comment]
> which system ? Retrobat, Batocera or Emuelec ? Le jeu. 14 avr. 2022 à 15:11, Thiago Castro ***@***.***> a écrit :
> […](#)

Emuelec

**Comment by EvilDindon** [comment]
done
