### ISSUE TITLE
Skraper does not download three images

### ISSUE THREAD

**Issue by thytetgc** [EvilDindon/ES-THEME-ARCADEPLANET#2]
You ask to SCRATCH, SCREENSHOT, BOX 2D, WHEEL.

But the PC program Skraper uses only the first two images.

How can I list the three in the gamelist.xml?

**Comment by EvilDindon** [comment]
Scrape within batocera directly using screenscraper. Just create a free
account on screenscraper, it's fast and easy.

https://www.screenscraper.fr/

Le ven. 8 avr. 2022 à 20:25, Thiago Castro ***@***.***> a
écrit :
