### ISSUE TITLE
Additional systems? Hikaru and Naomi 2?

### ISSUE THREAD

**Issue by mattborkin** [EvilDindon/ES-THEME-ARCADEPLANET#3]
Hello.

I wasn't sure if your theme automatically came with all of the systems that are supported in RetroBat 4.0. But, I noticed that Hikaru and Naomi 2 are not in your theme. 

Before I edit it and make them myself, I was just curious if you had plans for them. 

This is THE BEST theme for RetroBat. No question about that. Thank you !

**Comment by mattborkin** [comment]
No worries at all - I was just checking.

If you need any help on tracking down logos or controller pics or
suggestions or anything like that, please let me know and I would love to
help out if I ab able.

Thanks again,

Matt!

**Comment by EvilDindon** [comment]
Done

**Comment by mattborkin** [comment]
Thank you!!!
