### ISSUE TITLE
Random Art  Only works in Horizontal. Not Vertical?

### ISSUE THREAD

**Issue by almulder** [EvilDindon/ES-THEME-ARCADEPLANET#6]
The random art only seems to work in horizontal and not vertical, is this normal?

Also the different Styles all seem to do the same thing, I see not difference
		ease in and out, crossover, crossoverx2

Just thought I would report

**Comment by almulder** [comment]
Just updated and now I see you have already fixed the issue. :) My Bad

**Comment by EvilDindon** [comment]
Yeah the random art only work for now on horizontal view.
The animation style bug is fixed now.
Best one is ease in and out imo
