### ISSUE TITLE
Spinner and Trackball Collections

### ISSUE THREAD

**Issue by almulder** [EvilDindon/ES-THEME-ARCADEPLANET#7]
Seen all the updates, Looking good.

Wife had a great thought. A collection for games that the spinner can be used on and another of ones the trackball can be used on.

If you could make these 2 collections,

And possibly Killer Instinct?

Thanks again for your hard work. And no rush on 5:4 for arcade1up systems, I was able to mod what I needed to make it look good.

**Comment by EvilDindon** [comment]
Ok I'll work on these specific collections.
Not sure for KI though, a 2 games collection is too few imo

**Comment by EvilDindon** [comment]
4:3 and 5:4 ratios will be implemented once all systems are themed

**Comment by EvilDindon** [comment]
Hi. Trackball and Spinner custom collections are themed
